### PR TITLE
Reorganise common chapters into subdirectories

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
The guide is starting to get pretty big (which is awesome!), with loads of `traits-*.md` and `mir-*.md` chapters. This just moves the chapters into their own subdirectories.

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
I assume travis will fail at this point. The link checker says there are currently 67 broken links.

<details>
<summary>Broken Links</summary>
<pre>
<code>There were 67 broken links:
rustc-driver.md#43: "appendix-stupid-stats.html" doesn't exist
type-inference.md#109: "trait-resolution.html" doesn't exist
traits/resolution.md#9: "./traits.html" doesn't exist
traits/caching.md#23: "./trait-resolution.html" doesn't exist
traits/caching.md#34: "./trait-resolution.html" doesn't exist
traits/index.md#7: "./trait-resolution.html" doesn't exist
traits/index.md#16: "./traits-lowering-to-logic.html" doesn't exist
traits/index.md#18: "./traits-goals-and-clauses.html" doesn't exist
traits/index.md#20: "./traits-lowering-rules.html" doesn't exist
traits/index.md#22: "./traits-canonical-queries.html" doesn't exist
traits/index.md#26: "./traits-associated-types.html" doesn't exist
traits/index.md#29: "./traits-regions.html" doesn't exist
traits/lowering-to-logic.md#170: "./traits-bibliography.html" doesn't exist
traits/lowering-to-logic.md#171: "./traits-bibliography.html" doesn't exist
traits/goals-and-clauses.md#5: "./traits-lowering-to-logic.html" doesn't exist
traits/goals-and-clauses.md#35: "./traits-bibliography.html" doesn't exist
traits/goals-and-clauses.md#83: "./traits-lowering-rules.html" doesn't exist
traits/goals-and-clauses.md#85: "./traits-associated-types.html" doesn't exist
traits/goals-and-clauses.md#88: "./traits-associated-types.html" doesn't exist
traits/goals-and-clauses.md#90: "./traits-associated-types.html" doesn't exist
traits/goals-and-clauses.md#94: "./traits-lowering-rules.html" doesn't exist
traits/goals-and-clauses.md#149: "./traits-lowering-rules.html" doesn't exist
traits/canonical-queries.md#10: "./traits-associated-types.html" doesn't exist
traits/canonical-queries.md#93: "./traits-slg.html" doesn't exist
traits/canonical-queries.md#118: "./traits-regions.html" doesn't exist
traits/canonicalization.md#5: "./traits-canonical-queries.html" doesn't exist
traits/canonicalization.md#44: "./appendix-background.html" doesn't exist
traits/canonicalization.md#89: "./traits-slg.html" doesn't exist
traits/canonicalization.md#90: "./traits-canonical-queries.html" doesn't exist
traits/canonicalization.md#120: "./traits-canonical-queries.html" doesn't exist
traits/lowering-rules.md#4: "./traits-goals-and-clauses.html" doesn't exist
traits/lowering-rules.md#5: "./traits-goals-and-clauses.html" doesn't exist
traits/lowering-rules.md#19: "./traits-goals-and-clauses.html" doesn't exist
traits/lowering-rules.md#36: "./traits-goals-and-clauses.html" doesn't exist
traits/lowering-rules.md#139: "./traits-goals-and-clauses.html" doesn't exist
traits/lowering-rules.md#190: "./traits-associated-types.html" doesn't exist
traits/lowering-module.md#4: "./traits-lowering-rules.html" doesn't exist
type-checking.md#5: "trait-resolution.html" doesn't exist
variance.md#3: "./appendix-background.html" doesn't exist
mir/index.md#25: "./appendix-background.html" doesn't exist
mir/index.md#38: "./appendix-background.html" doesn't exist
mir/index.md#210: "appendix-glossary.html" doesn't exist
mir/index.md#213: "appendix-glossary.html" doesn't exist
mir/passes.md#124: "mir-visitor.html" doesn't exist
mir/borrowck.md#45: "./appendix-glossary.html" doesn't exist
mir/borrowck.md#46: "./mir-regionck.html" doesn't exist
mir/borrowck.md#47: "./appendix-background.html" doesn't exist
mir/borrowck.md#51: "./mir-regionck.html" doesn't exist
mir/regionck.md#16: "appendix-background.html" doesn't exist
mir/regionck.md#132: "appendix-background.html" doesn't exist
mir/regionck.md#147: "./appendix-background.html" doesn't exist
mir/regionck.md#184: "./appendix-background.html" doesn't exist
appendices/glossary.md#8: "./appendix-background.html" doesn't exist
appendices/glossary.md#9: "./appendix-background.html" doesn't exist
appendices/glossary.md#12: "./appendix-background.html" doesn't exist
appendices/glossary.md#15: "./appendix-background.html" doesn't exist
appendices/glossary.md#17: "./appendix-background.html" doesn't exist
appendices/glossary.md#31: "./mir.html" doesn't exist
appendices/glossary.md#33: "./traits-associated-types.html" doesn't exist
appendices/glossary.md#35: "./mir-regionck.html" doesn't exist
appendices/glossary.md#37: "trait-resolution.html" doesn't exist
appendices/glossary.md#38: "./traits-goals-and-clauses.html" doesn't exist
appendices/glossary.md#39: "./mir.html" doesn't exist
appendices/glossary.md#41: "./appendix-background.html" doesn't exist
appendices/glossary.md#47: "./mir-regionck.html" doesn't exist
appendices/glossary.md#53: "./traits-goals-and-clauses.html" doesn't exist
appendices/glossary.md#60: "./appendix-background.html" doesn't exist
</code>
</pre>
</details>

**Comment by mark-i-m** [comment]
Another note: we should probably go hunting through the rust-lang/rust repo for references to the chapters and fix them too...

**Comment by mark-i-m** [comment]
Ping @Michael-F-Bryan 

Just want to make sure this doesn't bitrot

**Comment by mark-i-m** [comment]
@Michael-F-Bryan Ping again :)

**Pull request closed without merging**
