### PR TITLE
revised a jemalloc statement in how-to-build-and-run.md

### PR DESCRIPTION
**Pull request by kenta7777**
I revised a jemalloc statement concerned with creating config.toml.

### CODE REVIEW

**Comment by kenta7777** [comment]
Fixes #227.

**Comment by mark-i-m** [comment]
Thanks! r=me when Travis passes

**Comment by ehuss** [comment]
The default is off, right?  Is there any reason to even mention jemalloc?

**Comment by mark-i-m** [comment]
It's a fair question. This was originally included by Niko, so my inclination is to keep it unless you feel strongly about it...

**Comment by ehuss** [comment]
> It's a fair question. This was originally included by Niko, so my inclination is to keep it unless you feel strongly about it...

It was included because the default was "on", and turning it off can help with development.  Now that it is off by default, I don't see a reason to mention it (there are many other settings in the config that aren't mentioned because the defaults are fine).  Also, this PR removes the original comment (which was unique to this guide) that explains why you would turn it off, and replaces it with a comment that is confusing to me (the way I read it it, it implies that it is *adding* jemalloc) — the other comments explain what it does, this one explains what it *doesn't* do.

**Comment by mark-i-m** [comment]
I see what you mean. So @kenta7777 could you actually just remove these lines altogether?

**Comment by kenta7777** [comment]
@mark-i-m Certainly. I'll remove these lines.

**Pull request merged**
