### PR TITLE
Adding ICH to the glossary.

### PR DESCRIPTION
**Pull request by avborhanian**

### CODE REVIEW

**Comment by mark-i-m** [comment]
Thanks! Would it be possible add an extra sentence like "ICHs are used for __"?

**Comment by avborhanian** [comment]
Sure, how about

ICHs are used as fingerprints for things such as HIR and crate metadata, to see if things hashed are equal or not.

**Comment by mark-i-m** [comment]
That's great! Thanks :)

I would even add just a bit more to that: "ICHs are used as fingerprints for things such as HIR and crate metadata, to check if changes have been made. This is useful in incremental compilation to see if part of a crate has changed and should be recompiled."

**Comment by mark-i-m** [comment]
(correct me if I'm wrong... I don't know much about incr. comp. :p)

**Comment by avborhanian** [comment]
Nah, that sounds perfect. I'll update the commit with that extra line.-

**Comment by mark-i-m** [comment]
Thanks! r=me when Travis I'm happy :)

**Pull request merged**
