### PR TITLE
Make max line length 100

### PR DESCRIPTION
**Pull request by mark-i-m**
r? @nikomatsakis 

cc @alexreg, since you were involved in the initial choice of 80c

### CODE REVIEW

**Comment by alexreg** [comment]
👍 from me

**Comment by mark-i-m** [comment]
Niko added this change to one of his PRs. Should merge soon.

**Comment by alexreg** [comment]
Are all existing lines going to be reformatted to be max 100 chars?

**Comment by mark-i-m** [comment]
I hope not. That would be a very hard diff to verify.

**Comment by nagisa** [comment]
in rustc we simply try to follow the style in the file. 100 is the limit
but it doesn't mean everything must be as close to the limit as possible.

**Pull request closed without merging**
