### PR TITLE
Augment notes one LLVM IR debugging

### LINKED ISSUE #162: Add notes about how to extract LLVM IR from rustc
I've posted some notes here: https://github.com/rust-lang/rust/issues/50422#issuecomment-402162648

### PR DESCRIPTION
**Pull request by mark-i-m**
Close #162 

r? @gnzlbg

### CODE REVIEW

**Comment by mark-i-m** [comment]
Oh man :( I messed up the rebase, so this also contains all the changes from #165... @gnzlbg If you want, I can try to remove those extra commits... or if you don't mind reviewing them... your call; let me know

**Comment by gnzlbg** [comment]
I don't mind :)

**Comment by gnzlbg** [comment]
LGTM, thanks!

**Comment by mark-i-m** [comment]
Thanks!

**Pull request merged**
