### PR TITLE
Update to mdbook 0.2

### LINKED ISSUE #109: Links don't work on github
as pointed out in https://github.com/rust-lang-nursery/rustc-guide/issues/100#issuecomment-378031147

We could make all of the links in the book absolute (always point to the guide) or we could leave them relative and just tell people to use the hosted mdbook version, rather than github... My personal leaning is towards the latter because it seems cleaner (easier to move the book later, easier to write, etc.)...

@nikomatsakis @Michael-F-Bryan Any thoughts?

cc @rajcspsg

### LINKED ISSUE #172: Sidebar subsection titles are cut-off
image

This screenshot shows 17.1.2 and 17.3.1, but there are several more subsection titles that are cut-off in the sidebar.

### PR DESCRIPTION
**Pull request by mark-i-m**
fixes #172, fixes #109

Dropped travis caches...

Currently it looks like linkcheck is passing despite broken links?

r? @Michael-F-Bryan

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
@mark-i-m `v0.2.1` is on [crates.io] so it looks like this PR should be unblocked now. Don't forget that you can enable checking remote links or going outside the book root via the config file.

[crates.io]: https://crates.io/crates/mdbook-linkcheck

**Comment by mark-i-m** [comment]
@Michael-F-Bryan Yes, a whitelist would be really useful. For now, I can just disable external link checking (unfortunately, that would also disabled checking links to compiler rustdocs), unless it would be a fast change.

**Comment by Michael-F-Bryan** [comment]
@mark-i-m I've uploaded a new release of `mdbook-linkcheck`. You should be able to skip false-positive URLs by adding a list of excluded URL patterns to your `book.toml`.

```toml
[output.linkcheck]
follow-web-links = true
exclude = [ "crates\\.io" ]
```

**Comment by mark-i-m** [comment]
:tada: :tada: :tada: Finally!

**Pull request merged**
