### PR TITLE
Add mdbook search.

### PR DESCRIPTION
**Pull request by ehuss**
May want to wait for 0.1.6 to be released since there is a minor CSS issue, but I thought this was nifty!

### CODE REVIEW

**Comment by mark-i-m** [comment]
Hmm... was waiting for 0.1.6, but I am beginning to kind of want this... should we still wait?

**Comment by mark-i-m** [comment]
@Michael-F-Bryan any thoughts?

**Comment by Michael-F-Bryan** [comment]
Well the CSS issues aren't super critical, they're more of an annoyance than anything else (rust-lang-nursery/mdBook#647) and are mostly solved by rust-lang-nursery/mdBook#648. I just want to test that PR locally before hitting merge, after which we'll probably do another release.

I don't see why we can't bump the `mdbook` version now, then bump it again when `mdbook` does another release. That search function is really really useful!

**Comment by mark-i-m** [comment]
@ehuss could you rebase?

**Comment by ehuss** [comment]
Updated!

**Comment by mark-i-m** [comment]
Thanks!

**Pull request merged**
